### ISSUE TITLE
MSRV Check

### ISSUE THREAD

**Issue by eitsupi** [JosiahParry/arrow-extendr#6]
Since Rust on CRAN is always outdated, it is very useful to have MSRV confirmed on CI.
Like this: apache/arrow-rs#4490

**Comment by JosiahParry** [comment]
Good point! This is the CI file to crib, right? 
https://github.com/eitsupi/arrow-rs/blob/a71864599f18c3181fc1d807f68285f032586b61/.github/workflows/rust.yml#L104

**Comment by eitsupi** [comment]
In short, just set `package.rust-version` in Cargo.toml and run `cargo-msrv verify`.
The arrow-rs repository required the CI to be run using a custom image, so that's what it is, but here's a faster version if there are no restrictions on the use of GitHub Action.

```yml
name: Check MSRV
on:
  push:
    branches:
      - main
    paths:
      - src/**/*.rs
      - Cargo.toml
  pull_request:
    branches:
      - main
    paths:
      - src/**/*.rs
      - Cargo.toml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-min-rust-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-msrv
      - name: Verify minimum rust version
        run: cargo-msrv verify
```
